version: "3.7"
services:
  hypermint:
    image: bluele/hypermint:unstable
    environment:
      TM_PARAMS: consensus.timeout_commit=1000ms,rpc.max_body_bytes=10000000,rpc.cors_allowed_origins=*,mempool.max_msg_bytes=10000000
    command: >
      /hmd start --home=/root/.hmd
      --log_level="*:info"
      --p2p.laddr="tcp://0.0.0.0:26656"
      --rpc.laddr="tcp://0.0.0.0:26657"
      --priv_validator_laddr=tcp://0.0.0.0:26658
    ports:
      - 26656:26656
      - 26657:26657
      - 26658:26658
    volumes:
      - "/tmp/hypermint:/root/.hmd"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:26657/status || exit 1"]
      start_period: "30s"
      retries: 10
      timeout: "3s"
      interval: "10s"
  tm-pkcs11:
    image: hypermint/tm-pkcs11:unstable
    command: --addr hypermint:26658 --chain-id test-chain-uAssCJ
    depends_on:
      - hypermint
    links:
      - hypermint
