version: "3.7"
services:
  hypermint:
    image: bluele/hypermint:unstable
    environment:
      TM_PARAMS: consensus.timeout_commit=1000ms,rpc.max_body_bytes=10000000,rpc.cors_allowed_origins=*,mempool.max_msg_bytes=10000000
    command: >
      /hmd start --home=/root/.hmd
      --log_level="*:error"
      --p2p.laddr="tcp://0.0.0.0:26656"
      --rpc.laddr="tcp://0.0.0.0:26657"
    ports:
      - 26656:26656
      - 26657:26657
    volumes:
      - "/tmp/hypermint:/root/.hmd"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:26657/status || exit 1"]
      start_period: "30s"
      retries: 3
      timeout: "5s"
      interval: "60s"
  tm-pkcs11:
    build:
      context: .
    command: --addr hypermint:26656
    depends_on:
      - hypermint
    links:
      - hypermint
